"""add plivo telephony sync fields

Revision ID: 32c7431faef6
Revises: f064d7315e1b
Create Date: 2026-08-31 13:39:22.095735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c7431faef6'
down_revision: Union[str, Sequence[str], None] = 'f064d7315e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('phone_numbers', sa.Column('dograh_phone_number_id', sa.String(length=50), nullable=True))
    op.add_column('tenant_provider_credentials', sa.Column('dograh_telephony_config_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_provider_credentials', 'dograh_telephony_config_id')
    op.drop_column('phone_numbers', 'dograh_phone_number_id')
    op.drop_column('phone_numbers', 'country_code')
    # ### end Alembic commands ###
